#!/bin/sh
set -eu
set -x
this_args="$@"
this_dir=$(dirname $(readlink -f $0))
root=$1;shift
target=$1;shift
dest=$1;shift
git -C $root clean -xdf .
cd $root
if [ -n "$target" ]; then
    env CC=$target-cc LD=$target-ld AS=$target-as ./configure --target=$target --host=x86_64
else
    env ./configure --target=$target --host=x86_64
fi
headers=$(make -f $this_dir/Makefile.show -C runtime COMPUTE_DEPS=false --no-print-directory BUILT_HEADERS.show)
make -C runtime COMPUTE_DEPS=false --no-print-directory $headers
sed -i 's/\(OCAML_STDLIB_DIR\)/\1 ""/' runtime/build_config.h
cd $this_dir
rm -rf $dest
mkdir -p $dest/runtime/caml
for f in\
 $headers\
 caml/m.h\
 caml/s.h\
 caml/version.h\
 ; do
 cp -pv $root/runtime/$f $dest/runtime/$f
done
cflags=$(make -f $this_dir/Makefile.show -C $root/runtime COMPUTE_DEPS=false --no-print-directory OC_CFLAGS.show)
sources=$(make -f $this_dir/Makefile.show -C $root/runtime COMPUTE_DEPS=false --no-print-directory BYTECODE_C_SOURCES.show)
inc="$dest/ocaml.inc"
echo "# This file is autogenerated by $0 $this_args" >$inc
echo "OCAML_ROOT=$root" >> $inc
echo "OCAML_CFLAGS=$cflags -I$root/runtime -I$dest/runtime/caml" >> $inc
echo "OCAML_RUNTIME_SOURCES=$sources" >> $inc
echo git -C $root clean -xdf .
