name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: devcontainer
      uses: ./.github/workflows/actions/devcontainer
      id: devcontainer
    - name: setup
      run: |
        echo 'EXEC=${{ steps.devcontainer.outputs.exec }}' >> $GITHUB_ENV
    - name: download
      run: |
        ${{ env.EXEC }} make -C lib/bindings/ download
    - name: build
      run: |
        ${{ env.EXEC }} make
    - name: run
      run: |
        ${{ env.EXEC }} make run
