name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: devcontainer
      uses: ./.github/workflows/actions/devcontainer
      id: devcontainer
    - name: setup
      run: |
        echo 'EXEC=${{ steps.devcontainer.outputs.exec }}' >> $GITHUB_ENV
    - name: build
      run: |
        ${{ env.EXEC }} make
    - name: run
      run: |
        ${{ env.EXEC }} make run
    - name: top
      run: |
        echo 'Example.Hello.print ();;' | ${{ env.EXEC }} make top
    - name: utop
      run: |
        echo 'Example.Hello.print ();;' | ${{ env.EXEC }} make utop
    - name: native
      run: |
        ${{ env.EXEC }} make ffi.native
        ${{ env.EXEC }} make WITH_VALGRIND=y ffi.run.native
    - name: arm
      run: |
        ${{ env.EXEC }} make ffi.arm
        ${{ env.EXEC }} make ffi.run.arm
    - name: aarch64
      run: |
        ${{ env.EXEC }} make ffi.aarch64
        ${{ env.EXEC }} make ffi.run.aarch64
    - name: i386
      run: |
        ${{ env.EXEC }} make ffi.i386
        ${{ env.EXEC }} make ffi.run.i386
    - name: x86_64
      run: |
        ${{ env.EXEC }} make ffi.x86_64
        ${{ env.EXEC }} make ffi.run.x86_64
