name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: devcontainer
      uses: ./.github/workflows/actions/devcontainer
      id: devcontainer
    - name: setup
      run: |
        echo 'EXEC=${{ steps.devcontainer.outputs.exec }}' >> $GITHUB_ENV
    - name: build
      run: |
        ${{ env.EXEC }} make
    - name: run
      run: |
        ${{ env.EXEC }} make run
    - name: top
      run: |
        echo 'Example.Hello.print ();;' | ${{ env.EXEC }} make top
    - name: utop
      run: |
        echo 'Example.Hello.print ();;' | ${{ env.EXEC }} make utop
    - name: df
      run: |
        ${{ env.EXEC }} df -h
        ${{ env.EXEC }} time make df.run
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: setup
      run: |
        sudo apt-get update
        sudo apt-get -o Acquire::Retries=3 -y install --no-install-recommends ocaml-nox
    - name: bytecode
      run: |
        make df.byte
    - name: native
      run: |
        make df.native
