name: images

on:
  push:
    branches:
      - '**'

jobs:
  versions:
    uses: ./.github/workflows/ocaml-versions.yml
  devcontainer:
    needs: versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        ocaml_version: ${{ fromJson(needs.versions.outputs.versions) }}
    permissions:
      packages: write
    steps:
    - name: checkout
      uses: actions/checkout@v6
      with:
        submodules: true
    - name: image
      uses: ./.github/workflows/actions/devcontainer
      env:
        OCAML_VERSION: ${{ matrix.ocaml_version }}
      with:
        variant: ${{ matrix.ocaml_version }}
        password: ${{ secrets.GITHUB_TOKEN }}
